# Generated by Django 4.1.7 on 2023-05-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=50, verbose_name='Nombre proyecto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha inicio')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='proyecto',
            field=models.ManyToManyField(blank=True, related_name='proyecto_empleado', to='empleado.proyecto'),
        ),
    ]
